lessons:
  target: production
  outputs:
    production:
      dataset: dbt_production
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cultivated-link-373708
      threads: 60
      type: bigquery